
/*TABELA USUARIO*/
CREATE TABLE USUARIO
(
idUsuario SMALLINT NOT NULL,
nome VARCHAR(50) NOT NULL,
login VARCHAR(20) NOT NULL,
senha VARCHAR(20) NOT NULL,
PRIMARY KEY (idUsuario),
CONSTRAINT usuario_uk
	  UNIQUE (login , senha)
);

/*TABELA AGÊNCIA*/
CREATE TABLE AGENCIA
(
idAgencia SMALLINT NOT NULL,
nome VARCHAR(25) NOT NULL,
cidade VARCHAR(30) NOT NULL,
estado VARCHAR(30) NOT NULL,
pais VARCHAR (25) NOT NULL,
idCidade SMALLINT NOT NULL,
PRIMARY KEY (idAgencia)
);

/*TABELA GRUPO*/
CREATE TABLE GRUPO
(
idGrupo SMALLINT NOT NULL,
nome VARCHAR(40) NOT NULL,
tarifaLivre numeric(10 , 2) NOT NULL,
tarifaControlada numeric(10 , 2) NOT NULL,
PRIMARY KEY (idGrupo)
);

/*TABELA VEICULO*/

CREATE SEQUENCE veiculo_seq;

CREATE TABLE VEICULO
(
idVeiculo SMALLINT DEFAULT nextval('veiculo_seq') NOT NULL,
fabricante VARCHAR(50) NOT NULL,
placa VARCHAR(10) NOT NULL,
cidade VARCHAR(30) NOT NULL,
km VARCHAR(5) NOT NULL,
chassi VARCHAR(17) NOT NULL,
modelo VARCHAR(20) NOT NULL,
estado varchar(30) NOT NULL,
idGrupoFK SMALLINT NOT NULL,
PRIMARY KEY (idVeiculo)
);

/*TABELA VEICULO_AGENCIA*/

CREATE SEQUENCE veiculo_agencia_seq;

CREATE TABLE VEICULO_AGENCIA
(
idVeiculoAg SMALLINT DEFAULT nextval('veiculo_agencia_seq') NOT NULL,
idVeiculoFK SMALLINT  NOT NULL,
idAgenciaFK SMALLINT  NOT NULL,
PRIMARY KEY (idVeiculoAg),
CONSTRAINT veiculo_agencia_uk
	  UNIQUE (idVeiculoFK , idAgenciaFK)
);

CREATE SEQUENCE cliente_seq;

/*TABELA CLIENTE*/
CREATE TABLE CLIENTE
(
idCliente SMALLINT DEFAULT nextval('cliente_seq') NOT NULL,
nome VARCHAR(50) NOT NULL,
registro VARCHAR(18) NOT NULL,
telefone VARCHAR(11) NOT NULL,
email VARCHAR(40) NOT NULL,
tipo VARCHAR(2) NOT NULL,
status CHAR (1) NOT NULL,
PRIMARY KEY (idCliente) ,
CONSTRAINT registro_uk
	  UNIQUE (registro)
);

/*TABELA PF*/
CREATE SEQUENCE pf_seq;

CREATE TABLE PF
(
idPF SMALLINT DEFAULT nextval('pf_seq') NOT NULL,
idClienteFK SMALLINT  NOT NULL,
sexo CHAR(1) NOT NULL,
dtaNascimento DATE NOT NULL,
rg VARCHAR(15) NOT NULL,
numHabilitacao VARCHAR(11) NOT NULL,
estadoEmissor VARCHAR(2) NOT NULL,
primeiraHabilitacao DATE NOT NULL,
validadeCartMotorista DATE NOT NULL,
PRIMARY KEY (idPF) ,
CONSTRAINT rg_uk
	  UNIQUE (rg)
);

/*TABELA PJ*/

CREATE SEQUENCE pj_seq;

CREATE TABLE PJ
(
idPJ SMALLINT DEFAULT nextval('pj_seq') NOT NULL,
idClienteFK SMALLINT NOT NULL,
razaoSocial VARCHAR(70) NOT NULL,
PRIMARY KEY (idPJ)
);

/*TABELA FORMA_PAGAMENTO*/

CREATE SEQUENCE formaPagamento_seq;

CREATE TABLE FORMA_PAGAMENTO
(
idFormaPagamento SMALLINT DEFAULT nextval('formaPagamento_seq') NOT NULL,
tipo VARCHAR(20) NOT NULL,
total NUMERIC(10,2) NOT NULL,

PRIMARY KEY (idFormaPagamento)
);

/*TABELA CHEQUE*/

CREATE SEQUENCE cheque_seq;

CREATE TABLE CHEQUE
(
idCheque SMALLINT DEFAULT nextval('cheque_seq') NOT NULL,
nomeBanco VARCHAR(20) NOT NULL,
numAgencia VARCHAR(6) NOT NULL,
numCCO VARCHAR(10) NOT NULL,
nomeTitular VARCHAR(50) NOT NULL,
cpfTitular VARCHAR(14) NOT NULL,
foneTitular VARCHAR(11) NOT NULL,
idFormaPagamentoFK SMALLINT NOT NULL,

PRIMARY KEY (idCheque)
);


/*TABELA LOCAÇÃO*/

CREATE SEQUENCE locacao_seq;

CREATE TABLE LOCACAO
(
idLocacao SMALLINT DEFAULT nextval('locacao_seq') NOT NULL,
tipoTarifa VARCHAR(14) NOT NULL,
dtaRetirada TIMESTAMP not null,
dtaPrevDevolucao TIMESTAMP not null,
total NUMERIC(10,2) not null,
idAgenciaDevolucaoFK SMALLINT  NOT NULL,
idAgenciaRetiradaFK SMALLINT  NOT NULL,
idFormPagFK SMALLINT  NOT NULL,
idVeiculoAgFK SMALLINT  NULL,
idClienteFK SMALLINT  NOT NULL,
kmInicialControlado INTEGER NULL,
PRIMARY KEY (idLocacao)
);

/*TABELA DEVOLUÇÃO*/

CREATE SEQUENCE devolucao_seq;

CREATE TABLE DEVOLUCAO
(
idDevolucao SMALLINT DEFAULT nextval('devolucao_seq') NOT NULL,
dtaDevolucao TIMESTAMP not null,
total NUMERIC(10,2) not null,
idLocacaoFK SMALLINT NOT NULL,
idFormPagFK SMALLINT NULL,
idAgenciaDevolucaoFK SMALLINT NOT NULL,
PRIMARY KEY (idDevolucao) ,
CONSTRAINT idLocacaoFK_UK
	  UNIQUE (idLocacaoFK)
);

/*TABELA CONDUTOR*/

CREATE SEQUENCE condutor_seq;

CREATE TABLE CONDUTOR
(
idCondutor SMALLINT DEFAULT nextval('condutor_seq') NOT NULL,
idLocacaoFK SMALLINT  NOT NULL,
idVeiculoAgFK SMALLINT  NOT NULL,
idPfFK SMALLINT  NOT NULL,
total NUMERIC(10,2) NOT NULL,
kmInicialControlado INTEGER NULL,
PRIMARY KEY (idCondutor) ,
CONSTRAINT condutor_uk
  UNIQUE (idLocacaoFK , idPfFK)
) ;


/*FOREIGN KEY DO GRUPO.idGrupo = VEICULO.idGrupoFK*/
ALTER TABLE VEICULO ADD FOREIGN KEY (idGrupoFK)
  REFERENCES GRUPO (idGrupo)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

/*FOREIGN KEY DO VEICULO.idVeiculo = VEICULO_AGENCIA.idVeiculoFK*/
ALTER TABLE VEICULO_AGENCIA ADD FOREIGN KEY (idVeiculoFK)
  REFERENCES VEICULO (idVeiculo)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

/*FOREIGN KEY DO AGENCIA.idAgencia = VEICULO_AGENCIA.idAgenciaFK*/
ALTER TABLE VEICULO_AGENCIA ADD FOREIGN KEY (idAgenciaFK)
  REFERENCES AGENCIA (idAgencia)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

/*FOREIGN KEY DO Cliente.idCliente = PF.idClienteFK*/
ALTER TABLE PF ADD FOREIGN KEY (idClienteFK)
  REFERENCES Cliente (idCliente)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

/*FOREIGN KEY DO Cliente.idCliente = PJ.idClienteFK*/
ALTER TABLE PJ ADD FOREIGN KEY (idClienteFK)
  REFERENCES Cliente (idCliente)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

/*FOREIGN KEY DO FORMA_PAGAMENTO.idFormaPagamento = CHEQUE.idFormaPagamentoFK*/
ALTER TABLE CHEQUE ADD FOREIGN KEY (idFormaPagamentoFK)
  REFERENCES FORMA_PAGAMENTO (idFormaPagamento)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

/*FOREIGN KEY DO Agencia.idAgencia = Locacao.idAgenciaDevolucaoFK*/
ALTER TABLE LOCACAO ADD FOREIGN KEY (idAgenciaDevolucaoFK)
  REFERENCES AGENCIA (idAgencia)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

/*FOREIGN KEY DO Agencia.idAgencia = Locacao.idAgenciaRetiradaFK*/
ALTER TABLE LOCACAO ADD FOREIGN KEY (idAgenciaRetiradaFK)
  REFERENCES AGENCIA (idAgencia)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

/*FOREIGN KEY DO FORMA_PAGAMENTO.idFormaPagamento = Locacao.idFormPagFK*/
ALTER TABLE LOCACAO ADD FOREIGN KEY (idFormPagFK)
  REFERENCES FORMA_PAGAMENTO (idFormaPagamento)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

/*FOREIGN KEY DO VEICULO_AGENCIA.idVeiculoAg = Locacao.idVeiculoAgFK*/
ALTER TABLE LOCACAO ADD FOREIGN KEY (idVeiculoAgFK)
  REFERENCES VEICULO_AGENCIA (idVeiculoAg)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

/*FOREIGN KEY DO CLIENTE.idCliente = Locacao.idClienteFK*/
ALTER TABLE LOCACAO ADD FOREIGN KEY (idClienteFK)
  REFERENCES CLIENTE (idCliente)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

/*FOREIGN KEY DO FORMA_PAGAMENTO.idFormaPagamento = DEVOLUCA.idFormPagFK*/
ALTER TABLE DEVOLUCAO ADD FOREIGN KEY (idFormPagFK)
  REFERENCES FORMA_PAGAMENTO (idFormaPagamento)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

/*FOREIGN KEY DO AGENCIA.idAgencia = DEVOLUCAo.idAgenciaDevolucaoFK*/
ALTER TABLE DEVOLUCAO ADD FOREIGN KEY (idAgenciaDevolucaoFK)
  REFERENCES AGENCIA (idAgencia)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

/*FOREIGN KEY DO LOCACAO.idLocacao = DEVOLUCAO.idLocacaoFK*/
ALTER TABLE DEVOLUCAO ADD FOREIGN KEY (idLocacaoFK)
  REFERENCES LOCACAO (idLocacao)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

/*FOREIGN KEY DO LOCACAO.idLocacao = CONDUTOR.idLocacaoFK*/
ALTER TABLE CONDUTOR ADD FOREIGN KEY (idLocacaoFK)
  REFERENCES LOCACAO (idLocacao)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

/*FOREIGN KEY DO VEICULO_AGENCIA.idVeiculoAg = CONDUTOR.idVeiculoAgFK*/
ALTER TABLE CONDUTOR ADD FOREIGN KEY (idVeiculoAgFK)
  REFERENCES VEICULO_AGENCIA (idVeiculoAg)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;

/*FOREIGN KEY DO PF.idPf = CONDUTOR.idPfFK*/
ALTER TABLE CONDUTOR ADD FOREIGN KEY (idPfFK)
  REFERENCES PF (idPf)
  ON DELETE RESTRICT
  ON UPDATE RESTRICT;